In [94]:
import numpy as np

In [2]:
my_arr = np.arange(1000000) #1 million values


In [50]:
my_list = list(range(1000000))

In [51]:
%time for _ in range(10): my_arr2 = my_arr * 2 

Wall time: 42 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.52 s


In [53]:
#Elapsed real time, real time, wall-clock time, or wall time is the actual time taken from the 
#start of a computer program to the end. In other words, 
#it is the difference between the time at which a task finishes and the time at which the task started.

In [6]:
data = np.random.randn(2, 3)

In [7]:
data

array([[-0.39185391,  1.24323116,  0.37719908],
       [ 1.74930614, -0.50924807, -0.49433599]])

One of the key features of NumPy is its N-dimensional array object, or ndarray,
which is a fast, flexible container for large datasets in Python. Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements.

In [8]:
data*10


array([[-3.91853913, 12.43231162,  3.77199082],
       [17.49306136, -5.09248068, -4.9433599 ]])

In [9]:
data+data

array([[-0.78370783,  2.48646232,  0.75439816],
       [ 3.49861227, -1.01849614, -0.98867198]])

In [10]:
data.shape

(2, 3)

In [54]:
data.size

6

In [11]:
data.dtype

dtype('float64')

numpy array uses significantly less memory

In [59]:
#import time
import sys

In [78]:
s=range(1000)
print(sys.getsizeof(s))
print(len(s))
print(sys.getsizeof(s)*len(s))

48
1000
48000


In [67]:
d=np.arange(1000)
print(d.itemsize)
print(d.size)
print(d.size*d.itemsize)

4
1000
4000


# Creating ndarrays

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
#Nested sequences, like a list of equal-length lists, will be converted into a multidimensional
#array:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2=np.array(data2)

In [16]:
arr2.ndim  
#to check dimensions of array created

2

In [17]:
arr2.shape

(2, 4)

In [18]:
arr2.size


8

In [19]:
#Unless explicitly specified, np.array tries to infer a good datatype
#for the array that it creates. The data type is stored in a special dtype metadata
#object;

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
#In addition to np.array, there are a number of other functions for creating new
#arrays. As examples, zeros and ones create arrays of 0s or 1s, respectively, with a
#given length or shape. empty creates an array without initializing its values to any particular
#value. To create a higher dimensional array with these methods, pass a tuple
#for the shape:

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [73]:
x=np.ones((3, 6))
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [74]:
x.dtype

dtype('float64')

In [95]:
np.empty((2, 3)) #It’s not safe to assume that np.empty will return an array of all
                    #zeros. In some cases, it may return uninitialized “garbage” values.

array([[ 3.7, -1.2, -2.6],
       [ 0.5, 12.9, 10.1]])

In [26]:
np.empty((2, 3, 3))  #It’s not safe to assume that np.empty will return an array of all
                    #zeros. In some cases, it may return uninitialized “garbage” values.

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [88]:
np.empty(3)

array([ 1.25,  9.6 , 42.  ])

In [84]:
#arange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Data Types for ndarrays

The data type or dtype is a special object containing the information (or metadata,
data about data) the ndarray needs to interpret a chunk of memory as a particular
type of data:

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [29]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

#The numerical dtypes are named the way: a type name, like float or int, followed
by a number indicating the number of bits per element. int32 uses 32 bits and float64 uses 64 bits

In [32]:
#You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method:

In [33]:
arr = np.array([1, 2, 3, 4, 5])

In [34]:
arr.dtype

dtype('int32')

In [35]:
float_arr = arr.astype(np.float64)

In [36]:
float_arr.dtype

dtype('float64')

If you cast some floating-point
numbers to be of integer dtype, the decimal part will be truncated:

In [37]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [38]:
arr.dtype


dtype('float64')

In [39]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [40]:
arr.dtype

dtype('float64')

If you have an array of strings representing numbers, you can use astype to convert
them to numeric form:

In [41]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [42]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

It’s important to be cautious when using the numpy.string_ type,
as string data in NumPy is fixed size and may truncate input
without warning. pandas has more intuitive out-of-the-box behavior
on non-numeric data.

If casting were to fail for some reason (like a string that cannot be converted to
float64), a ValueError will be raised. Here I was a bit lazy and wrote float instead
of np.float64; NumPy aliases the Python types to its own equivalent data dtypes.

In [43]:
#You can also use another array’s dtype attribute:
int_array = np.arange(10)

In [44]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [45]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Calling astype always creates a new array (a copy of the data), even
if the new dtype is the same as the old dtype.

In [46]:
#There are shorthand type code strings you can also use to refer to a dtype:

In [47]:
empty_uint32 = np.empty(8, dtype='u4')

In [48]:
empty_uint32

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=uint32)

In [49]:
arr = np.array(['a', '2', '3'], dtype='i')
#If a type is given in which elements can't be casted then NumPy will raise a ValueError.
#'a' can not be converted to int

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#Create an array with data type string:

arr = np.array([1, 2, 3, 4], dtype='S')
#arr = np.array([1, 2, 3, 4])

print(arr)
#print(arr.dtype)

In [90]:
arr = np.array(['a', 'd'], dtype='S')
arr

array([b'a', b'd'], dtype='|S1')

In [96]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [93]:
np.eye(5) #creates square matrix with 1 in diagonals and 0 in non diagonal positions

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

contd...